version: '3'

services:
  dns-client:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      trabalho-redes:
        ipv4_address: 192.168.10.2
    volumes:
      - client-data:/data
      - ./resolv.conf:/etc/resolv.conf
    hostname: www.lumidoubleclient.com
    tty: true
    stdin_open: true
    command: >
      sh -c "
      export DEBIAN_FRONTEND=noninteractive &&
      apt-get update && 
      apt-get install -y dnsutils &&
      named -g"

  dns-server:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      trabalho-redes:
        ipv4_address: 192.168.10.3
    volumes:
      - server-data:/etc/bind
      - ./named.conf.local:/etc/bind/named.conf.local
      - ./db.lumidouble:/etc/bind/db.lumidouble
      - ./db.doublelumi:/etc/bind/db.doublelumi
    hostname: www.lumidoubleserver.com
    tty: true
    stdin_open: true
    command: >
      sh -c "
      export DEBIAN_FRONTEND=noninteractive &&
      apt-get update && 
      apt-get install -y dnsutils bind9 && 
      named -g"

  mail-server:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      trabalho-redes:
        ipv4_address: 192.168.10.4
    volumes:
      - ./setup-postfix.sh:/setup-postfix.sh
    hostname: lumidoublemailserver.com
    tty: true
    stdin_open: true
    ports:
      - 25:25
    command: >
      sh -c "
      export DEBIAN_FRONTEND=noninteractive &&
      apt-get update && 
      apt-get install -y dnsutils postfix mailutils dovecot-core dovecot-imapd net-tools thunderbird && 
      named -g"

  www-server:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      trabalho-redes:
        ipv4_address: 192.168.10.5
    volumes:
      - ./setup-apache2.sh:/setup-apache2.sh
      - ./create-html.sh:/create-html.sh
    hostname: www.lumidoublewwwserver.com
    tty: true
    stdin_open: true
    ports:
      - 80:80
    command: >
      sh -c "
      export DEBIAN_FRONTEND=noninteractive &&
      apt-get update && 
      apt-get install -y dnsutils apache2 && 
      named -g"

networks:
  trabalho-redes:
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24

volumes:
  client-data:
  server-data: