version: '3'

services:
  dns-client:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      trabalho-redes:
        ipv4_address: 192.168.10.2
    volumes:
      - client-data:/data
      - ./resolv.conf:/etc/resolv.conf
    hostname: client
    tty: true
    stdin_open: true
    command: >
      sh -c "
      export DEBIAN_FRONTEND=noninteractive &&
      apt-get update && 
      apt-get install -y dnsutils &&
      named -g"

  dns-server:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      trabalho-redes:
        ipv4_address: 192.168.10.3
    ports:
      - 5053:5053
    volumes:
      - server-data:/etc/bind
      - ./named.conf.local:/etc/bind/named.conf.local
      - ./db.lumidouble:/etc/bind/db.lumidouble
      - ./db.doublelumi:/etc/bind/db.doublelumi
    hostname: dns-server
    tty: true
    stdin_open: true
    command: >
      sh -c "
      export DEBIAN_FRONTEND=noninteractive &&
      apt-get update && 
      apt-get install -y dnsutils bind9 && 
      named -g"

  mail-server:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      trabalho-redes:
        ipv4_address: 192.168.10.4
    volumes:
      - ./setup-postfix.sh:/setup-postfix.sh
    hostname: mail-server
    tty: true
    stdin_open: true
    ports:
      - 25:25
    command: >
      sh -c "
      export DEBIAN_FRONTEND=noninteractive &&
      apt-get update && 
      apt-get install -y dnsutils postfix mailutils dovecot-core dovecot-imapd dovecot-pop3d net-tools thunderbird && 
      named -g"

  www-server:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      trabalho-redes:
        ipv4_address: 192.168.10.5
    volumes:
      - ./setup-apache2.sh:/setup-apache2.sh
      - ./create-html.sh:/create-html.sh
      - ./web-user.sh:/web-user.sh
      - ./config-htaccess.sh:/config-htaccess.sh
      - ./config-dominios.sh:/config-dominios.sh
    hostname: web-server
    tty: true
    stdin_open: true
    ports:
      - 80:80
    command: >
      sh -c "
      export DEBIAN_FRONTEND=noninteractive &&
      apt-get update && 
      apt-get install -y dnsutils apache2 && 
      named -g
      "

  firefox:
    image:  kasmweb/firefox:1.13.0
    networks:
      trabalho-redes:
        ipv4_address: 192.168.10.10
    dns: 192.168.10.3
    
    shm_size: 512m

    environment:
      - VNC_PW=password
    hostname: firefox
    ports:
      - 6902:6902

  thunderbird:
    image:  kasmweb/thunderbird:1.13.0
    networks:
      trabalho-redes:
        ipv4_address: 192.168.10.9
    dns: 192.168.10.3
    shm_size: 512m
    environment:
      - VNC_PW=password
    hostname: thunderbird
    ports:
      - 6901:6901

networks:
  trabalho-redes:
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24

volumes:
  client-data:
  server-data: