version: '3'

services:
  dns-client:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      trabalho-redes:
        ipv4_address: 192.168.10.2
    volumes:
      - client-data:/data
      - ./resolv.conf:/etc/resolv.conf
    hostname: www.lumidoubleclient.com
    tty: true
    stdin_open: true
    command: >
      sh -c "
      export DEBIAN_FRONTEND=noninteractive &&
      apt-get update && 
      apt-get install -y dnsutils && 
      named -g"

  dns-server:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      trabalho-redes:
        ipv4_address: 192.168.10.3
    volumes:
      - server-data:/etc/bind
      - ./named.conf.local:/etc/bind/named.conf.local
      - ./db.lumidouble:/etc/bind/db.lumidouble
      - ./db.doublelumi:/etc/bind/db.doublelumi
      - ./setup-postfix.sh:/setup-postfix.sh
      - ./setup-apache2.sh:/setup-apache2.sh
      - ./create-html.sh:/create-html.sh
    hostname: www.lumidoubleserver.com
    tty: true
    stdin_open: true
    command: >
      sh -c "
      export DEBIAN_FRONTEND=noninteractive &&
      apt-get update && 
      apt-get install -y dnsutils postfix apache2 && 
      named -g"

  # bind9:
  #   image: ubuntu/bind9:latest
  #   environment:
  #     - BIND9_USER=root
  #   ports:
  #     - "53:53/udp" 
  #   restart: unless-stopped

networks:
  trabalho-redes:
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24

volumes:
  client-data:
  server-data: